apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-app
  namespace: shop-ns
  labels:
    app: recommendations-app
    version: dev
spec:
  selector:
    matchLabels:
      app: recommendations-app
  template:
    metadata:
      labels:
        app: recommendations-app
    spec:
      containers:
      - name: recommendations-app
        image: gcr.io/gothic-scheme-375315/recommendations:dev
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 8082
