apiVersion: v1
kind: Service
metadata:
  name: recommendations-svc
  namespace: shop-ns
  labels:
    app: recommendations-app
spec:
    selector:
        app: recommendations-app
    ports:
    - port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendations-sa
  namespace: shop-ns