apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: recommendations-vsvc
  namespace: shop-ns
spec:
    hosts:
    - recommendations-svc
    http:
    - route:
        - destination:
            host: recommendations-svc
            subset: dev
          weight: 50
        - destination:
            host: recommendations-svc
            subset: dev2
          weight: 50
      retries:
        attempts: 0
#      timeout: 1000ms