apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: recommendations-vsvc
spec:
    hosts:
    - recommendations-vsvc
    http:
    - route:
        - destination:
            host: recommendations-svc