apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
  namespace: shop-ns
  labels:
    app: front-app
    version: dev
spec:
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - name: front-app
        image: gcr.io/gothic-scheme-375315/front:dev
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
        envFrom:
        - configMapRef:
            name: front-config
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 2
        readinessProbe:
            httpGet:
                path: /actuator/health/liveness
                port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 2
