# See more at https://istio.io/docs/reference/config/networking/virtual-service/
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: front-vsvc
spec:
  hosts:
  - front-vsvc
  http:
  - route:
    - destination:
        host: front-svc