redirectUri: ${REDIRECT_URI:https://google.com}
issuerUri: ${ISSUER_URI:http://localhost:9000}
server:
  port: 9000

logging:
  level:
    org.springframework.security: trace
debug: true

spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/app1?authSource=admin
  security:
    oauth2:
      authorizationserver:
        client:
          messaging-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc"
                - "http://127.0.0.1:8080/authorized"
                - "https://oauth.pstmn.io/v1/callback"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "message.read"
                - "message.write"
            require-authorization-consent: true