openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
  description: API for managing products
paths:
  /products:
    get:
      summary: Get list of products
      description: Returns a list of ProductShort objects
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductShort'
components:
  schemas:
    ProductShort:
      type: object
      properties:
        title:
          type: string
          description: The title of the product
        shortDescription:
          type: string
          description: A short description of the product
        price:
          type: number
          format: float
          description: The price of the product