apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-repo-app
  namespace: shop-ns
  labels:
    app: product-repo-app
    version: dev
spec:
    selector:
        matchLabels:
          app: product-repo-app
          version: dev
    template:
        metadata:
          labels:
              app: product-repo-app
              version: dev
        spec:
          serviceAccountName: product-repo-sa
          containers:
          - name: product-repo
            image: gcr.io/gothic-scheme-375315/product-repo:dev
            imagePullPolicy: Always
            resources:
              requests:
                memory: "128Mi"
                cpu: "5m"
            ports:
            - containerPort: 8081
            livenessProbe:
              httpGet:
                path: /actuator/health/readiness
                port: 8081
              initialDelaySeconds: 20
              periodSeconds: 10
              failureThreshold: 5
            readinessProbe:
                httpGet:
                    path: /actuator/health/liveness
                    port: 8081
                initialDelaySeconds: 20
                periodSeconds: 10
                failureThreshold: 5