apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-repo-vsvc
spec:
  hosts:
  - product-repo-vsvc
  http:
  - route:
      - destination:
          host: product-repo-svc